version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - service
      - assets
  service:
    image: server
    build:
      wallet/
    depends_on:
      - db
    env_file:
    - common.env
  assets:
    image: ui
    build: 
      wallet_ui/
  db:
    image: sameersbn/mysql:latest
    env_file:
    - common.env

